### PR TITLE
Upload GeoJSON - Added CRS check

### LINKED ISSUE #1366: [Import GeoJSON] Fail with error if not in WGS84 projection
See also #718

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #1366

### CODE REVIEW

File: functions/src/import-geojson.ts [hunk 1]
```diff
@@ -81,25 +81,64 @@ export function importGeoJsonCallback(
...
 
     file
-      .pipe(JSONStream.parse(['features', true], undefined))
-      .on('data', (geoJsonLoi: any) => {
-        try {
-          if (geoJsonType !== 'FeatureCollection') {
+      .pipe(JSONStream.parse('crs', undefined))
+      .on(
+        'data',
+        (
```
Comment (gino-m) [inline functions/src/import-geojson.ts:105]: @rfontanarosa Now might be a good time to move this handler into its own function (`onGeoJsonCrs()`?)

File: functions/src/import-geojson.ts [hunk 2]
```diff
@@ -81,25 +81,64 @@ export function importGeoJsonCallback(
...
+                geoJsonCrs
+              )}'`
             );
           }
+        }
+      );
+
+    file
+      .pipe(JSONStream.parse(['features', true], undefined))
+      .on('data', (geoJsonLoi: any) => {
```
Comment (gino-m) [inline functions/src/import-geojson.ts:130]: Same here (`onGeoJsonFeature`?)

**Review by gino-m — CHANGES_REQUESTED** [review]
LGTM! Added a small code health tax if you don't mind :)

**Review by gino-m — APPROVED** [review]
🍾 !
