### PR TITLE
Edit survey edit job shows lois for wrong job

### LINKED ISSUE #1237: Edit survey -> Edit job -> Shows LOIs for wrong job (not selected one) even after refreshing page

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1237

https://github.com/google/ground-platform/assets/10047945/dccc07da-63cf-4972-b211-0b42031a01f7

### CODE REVIEW

File: web/src/app/pages/edit-survey/edit-job/edit-job.component.ts [hunk 1]
```diff
@@ -95,6 +100,19 @@ export class EditJobComponent {
         )
       )
     );
+
+    this.lois = await firstValueFrom(
```
Comment (nwkotto) [inline web/src/app/pages/edit-survey/edit-job/edit-job.component.ts:104]: Can you add a test to ensure that the correct lois are getting filtered and passed into the loi-selection component?

File: web/src/app/pages/create-survey/survey-loi/survey-loi.component.ts [hunk 2]
```diff
@@ -0,0 +1,42 @@
...
+export class SurveyLoiComponent {
+  lois$!: Observable<List<LocationOfInterest>>;
+
+  constructor(
+    readonly loiService: LocationOfInterestService,
+    readonly surveyService: SurveyService
+  ) {}
+
+  ngOnInit() {
+    this.lois$ = this.loiService
```
Comment (nwkotto) [inline web/src/app/pages/create-survey/survey-loi/survey-loi.component.ts:38]: Can you add a test here - guess you'll need to add a test file as well - for the lois getting fetched and passed into the component?

**Review by nwkotto — CHANGES_REQUESTED** [review]
Looks good! Thanks for making these changes -- the structure makes sense. Main request is just to add tests for the data that you're fetching and passing into the loi-selection component, especially since that was the issue in the first place.

File: web/src/app/pages/create-survey/survey-loi/survey-loi.component.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+      .getLocationsOfInterest$()
+      .pipe(map(lois => LocationOfInterestService.getLoisWithNames(lois)));
```
Comment (gino-m) [inline web/src/app/pages/create-survey/survey-loi/survey-loi.component.ts:40]: Can this be rolled into the service itself? ie expose a non-static method `getLoisWithLabels$`?

File: web/src/app/pages/edit-survey/edit-job/edit-job.component.ts [hunk 4]
```diff
@@ -95,6 +100,19 @@ export class EditJobComponent {
...
+      this.loiService.getLocationsOfInterest$().pipe(
+        map(lois => LocationOfInterestService.getLoisWithNames(lois)),
```
Comment (gino-m) [inline web/src/app/pages/edit-survey/edit-job/edit-job.component.ts:106]: Same here.

File: web/src/app/pages/edit-survey/edit-job/edit-job.component.ts [hunk 5]
```diff
@@ -95,6 +100,19 @@ export class EditJobComponent {
...
+        map(lois =>
+          List(
+            lois
+              .toArray()
+              .filter((loi: LocationOfInterest) => loi.jobId === this.jobId)
```
Comment (gino-m) [inline web/src/app/pages/edit-survey/edit-job/edit-job.component.ts:111]: This seems to be a roundabout way of getting the lois for he current job. Can we just expose a method in the service to do this? It could later be optimized there in the data layer if necessary.

File: web/src/app/services/loi/loi.service.ts [hunk 6]
```diff
@@ -79,6 +79,14 @@ export class LocationOfInterestService {
     return this.lois$;
   }
 
+  getJobLocationsOfInterest$(
+    jobId: string
+  ): Observable<List<LocationOfInterest>> {
+    return this.lois$.pipe(
```
Comment (gino-m) [inline web/src/app/services/loi/loi.service.ts:85]: I see you actually added it here; you can just call it from the component?

Nit: -> getLoisByJobId$()

**Review by gino-m — CHANGES_REQUESTED** [review]
LG, a few small edits

**Review by nwkotto — APPROVED** [review]

**Review by gino-m — APPROVED** [review]
