### PR TITLE
Fix extra divider elements in task submission view

### LINKED ISSUE #2298: Task list divider ignores non-existent/instructions tasks
Image

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #2298

Screenshot 2025-12-09 alle 13 57 32

### CODE REVIEW

File: web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts [hunk 1]
```diff
@@ -78,6 +78,17 @@ export class SubmissionPanelComponent implements OnInit, OnDestroy {
     );
   }
 
+  get submittedTasks() {
+    if (!this.tasks) {
+      return [];
+    }
+    console.log(this.tasks.toArray());
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts]: Please remove debug
