### PR TITLE
[Layer dialog] Order of multiple choice options changes unexpectedly

### LINKED ISSUE #579: [Layer dialog] Order of multiple choice options changes unexpectedly
**To Reproduce**
1. Click "+ Add layer"
2. Create a multiple choice question, define options
3. Save layer
4. Open layer dialog again via "Customize layer" in overflow menu.

**Expected behavior**
Order of options should be preserved

**Screenshots**
Order of options changes. Before save:
image

After reopening dialog:
image

@parulraheja98 Could you PTAL?

### PR DESCRIPTION
**Pull request by parulraheja98**
Closes #579

### CODE REVIEW

**Review by gino-m — CHANGES_REQUESTED** [review]
Awesome! One suggestion on how to simplify.

**Comment by parulraheja98** [comment]
@gino-m , thank you, I think the changes requested are missing.

File: web-ng/src/app/components/layer-dialog/layer-dialog.component.ts [hunk 1]
```diff
@@ -146,9 +146,17 @@ export class LayerDialogComponent implements OnDestroy {
     }
     this.form = this.layerService.getForm(this.layer);
     if (this.form) {
-      this.fields =
+      const fields =
         this.form?.fields.toList().sortBy(field => field.index) ||
         List<Field>();
+      fields.forEach((field, ind) => {
```
Comment (gino-m) [inline web-ng/src/app/components/layer-dialog/layer-dialog.component.ts:152]: Instead of rebuilding Fields with sorted multiple choice options, perhaps it's simpler to sort them in the constructor of MultipleChoice? This way the options in a give Field will always be in order. Wdyt?

**Review by gino-m — CHANGES_REQUESTED** [review]
Sorry, not sure how my comment got lost. Resending!

**Review by gino-m — APPROVED** [review]
Happy New Year, @parulraheja98. All LGTM! 🥳
