### PR TITLE
Fix crash when Firestore document contains null fields

### LINKED ISSUE #2048: [Feature] Handle null values in proto

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #2048

### CODE REVIEW

File: lib/src/firestore-to-proto.ts [hunk 1]
```diff
@@ -77,7 +77,7 @@ function toMessageValue(
   if (!descriptor.fields) return null;
   const field = descriptor.fields[fieldName];
   const fieldType = field?.type;
-  if (field.keyType) {
+  if (field?.keyType) {
     if (field.keyType !== 'string')
       return Error(`${field.keyType} map keys not supported`);
     // TODO: Check that firestoreValue is an object.
```
Comment (gino-m) [inline lib/src/firestore-to-proto.ts]: Can we also resolve this TODO while we're here?
