### PR TITLE
Fixes display/export of empty other option

### LINKED ISSUE #2099: [Download CSV] "Other" multiple choice values appear as blank
These values appear blank in the exported data when no user text is specified. 

Expected: "Other" or "Other: <user specified text>" (without <>).

@rfontanarosa

### PR DESCRIPTION
**Pull request by rfontanarosa**
Towards #2099

Screenshot 2024-11-25 alle 16 29 30

https://github.com/user-attachments/assets/3c81d29f-568f-4d56-89d0-1e21045d79e7

### CODE REVIEW

File: functions/src/export-csv.ts [hunk 1]
```diff
@@ -237,38 +237,37 @@ function getValue(
...
+  const {
+    textResponse,
+    numberResponse,
+    dateTimeResponse,
+    multipleChoiceResponses,
+    drawGeometryResult,
+    captureLocationResult,
+    takePhotoResult,
+  } = result;
+  if (textResponse) return textResponse.text ?? null;
```
Comment (gino-m) [inline functions/src/export-csv.ts:250]: The `if .. else if` idiom is safer in this case since it represents an exhaustive list of mutually exclusive possibilities.

File: functions/src/export-csv.ts [hunk 2]
```diff
@@ -293,8 +292,14 @@ function getMultipleChoiceValues(
     responses.selectedOptionIds?.map(
       id => getMultipleChoiceLabel(task, id) || '#ERR'
     ) || [];
-  if (responses.otherText && responses.otherText.trim() !== '')
-    values.push(responses.otherText);
+  // Ensure at least one value is present: if no values are selected and 'otherText' is empty, add 'Other' as a fallback.
```
Comment (gino-m) [inline functions/src/export-csv.ts:295]: Please add a note that this is a temporary workaround for an issue on the Android client and add a link to the bug.

File: web/src/app/converters/submission-data-converter.ts [hunk 3]
```diff
@@ -97,27 +97,24 @@ function taskDataPbToModelValue(
   } = taskData;
 
   if (textResponse) return textResponse.text;
-  else if (numberResponse) return numberResponse.number;
-  else if (dateTimeResponse)
+  if (numberResponse) return numberResponse.number;
```
Comment (gino-m) [inline web/src/app/converters/submission-data-converter.ts:100]: Same here re if..else

File: web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts [hunk 4]
```diff
@@ -107,22 +107,30 @@ export class SubmissionPanelComponent implements OnInit, OnDestroy {
     return this.getTaskSubmissionResult(task)!.value as MultipleSelection;
   }
 
+  getTaskMultipleChoiceOtherValue(task: Task): string | null {
+    const multipleSelection = this.getTaskSubmissionResult(task)!
+      .value as MultipleSelection;
+    // Ensure at least one value is present: if no values are selected and 'otherText' is empty, add 'Other' as a fallback.
+    if (multipleSelection.values.size === 0 && !multipleSelection.otherValue)
+      return 'Other';
+    if (multipleSelection.otherValue)
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts:116]: Please refactor duplicate logic into shared lib.

File: web/src/app/pages/terms/terms.component.ts [hunk 5]
```diff
@@ -44,7 +44,7 @@ export class TermsComponent implements OnInit {
   async ngOnInit() {
     const text = await this.dataStore.getTermsOfService();
 
-    this.termsOfServiceText = await parse(text.replace(/#NEWLINE#/g, '\n'));
+    this.termsOfServiceText = await parse(text);
```
Comment (gino-m) [inline web/src/app/pages/terms/terms.component.ts:47]: Is the `#NEWLINE#` workaround no longer needed?

**Review by gino-m — CHANGES_REQUESTED** [review]

File: web/src/app/pages/terms/terms.component.ts (hunk 5 above)
Comment (rfontanarosa) [reply web/src/app/pages/terms/terms.component.ts:47]: Yes, because I tried to programmatically insert the text and it didn't remove newline characters. So we don't need to do the same replacement in the Android version.

**Review by gino-m — APPROVED** [review]

File: functions/src/export-csv.ts (hunk 2 above)
Comment (gino-m) [reply functions/src/export-csv.ts:293]: @rfontanarosa Reminder to add a note here.

File: web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts (hunk 4 above)
Comment (rfontanarosa) [reply web/src/app/pages/main-page-container/main-page/secondary-side-panel/submission-panel/submission-panel.component.ts:117]: in another pr :)

**Review by gino-m — APPROVED** [review]
