### PR TITLE
Fix Property Generator when property is an Array/Object

### LINKED ISSUE #1897: WHISP data missing on new plots
Recently recorded plots are not showing WHISP data, just the name. Seems to be an issue in the layer between the registry and Ground

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #1897

### CODE REVIEW

File: functions/src/on-create-loi.ts [hunk 1]
```diff
@@ -51,6 +51,13 @@ export async function onCreateLoiHandler(
       properties,
       wkt
     );
+
+    Object.keys(properties).forEach(key => {
```
Comment (gino-m) [inline functions/src/on-create-loi.ts:55]: You could also use `filter()` to only modify the object properties and leave the rest along.

Comment (gino-m) [reply functions/src/on-create-loi.ts:55]: e.g. 
```ts
Object.keys(properties)
  .filter(key => typeof properties[key] === 'object')
  .forEach(key => { properties[key] = JSON.stringify(properties[key]); }
```

Does this work?

**Review by gino-m — APPROVED** [review]
