### PR TITLE
Handle issues when reading invalid data in Firestore.

### LINKED ISSUE #931: Handle issues when reading invalid data in Firestore
~"Quota exceeded" was being tripped but was only visible in the Chrome debug console on web. We should display these error to the user to help debugging.~

~See also https://github.com/google/ground-android/issues/1227~

~@DaoyuT We'll need to catch errors in Angular components which use Firebase. Import/export is out of scope of this request. We call Firebase in a few ways:~

~- [ ] Create helper to display error message with simple alert~
~- [ ] Call fro Rx streams onError and on thrown exceptions~

Rescoping as following to make more tractable:

- [x] Converter functions which throw errors should instead return `T | Error` 
- [x] Handle errors in caller of converters as follows:
  - [x] If creating a List<>, just log as error and don't add to list.
  - [x] If called directly on `pipe(map())`, we can add a helper `handleErrors` which returns `OperatorFunction<T, R>` to pass to pipe to log and skip.

### PR DESCRIPTION
**Pull request by DaoyuT**
fix #931

### CODE REVIEW

File: web/src/app/converters/firebase-data-converter.ts [hunk 1]
```diff
@@ -465,10 +465,32 @@ export class FirebaseDataConverter {
...
   }
 
+  private static toResults(job: Job, data: DocumentData): Map<string, Result> {
+    const submissionData = data.data ?? data.results ?? data.responses;
+    return Map<string, Result>(
+      keys(submissionData)
+        .map((taskId: string) => [
+          taskId as string,
+          FirebaseDataConverter.toResult(
+            job.tasks!.get(taskId)!,
```
Comment (gino-m) [inline web/src/app/converters/firebase-data-converter.ts:475]: We should also probably handle this case explicitly, and/or comment describing why this can never happen. I'd also suggest adding a brief comment to TSDoc that this method handles errors, i.e., caller doesn't need to catch.

Alternatively, we can have this method return `Map<String, Result | Error>` and let the caller filter and log.

File: web/src/app/converters/firebase-data-converter.ts [hunk 2]
```diff
@@ -465,10 +465,32 @@ export class FirebaseDataConverter {
...
+            submissionData[taskId]
+          ),
+        ])
+        .filter(([_, resultOrError]) => {
```
Comment (gino-m) [inline web/src/app/converters/firebase-data-converter.ts:479]: Can we refactor `filterConversionErrorAndLog` so that we can call it here?

File: web/src/app/services/data-store/data-store.service.ts [hunk 3]
```diff
@@ -455,4 +451,12 @@ export class DataStoreService {
     });
     return tasksMap;
   }
+
+  private filterConversionErrorAndLogError<T>(entityOrError: T | Error) {
```
Comment (gino-m) [inline web/src/app/services/data-store/data-store.service.ts:455]: Nit: `filterAndLogError` (the additional "Error" is clear from context, plus there's nothing specific to "conversion" here)

File: web/src/app/services/submission/submission.service.ts [hunk 4]
```diff
@@ -86,7 +86,13 @@ export class SubmissionService {
             )
           )
         )
-        .subscribe(o => this.selectedSubmission$.next(o))
+        .subscribe(o => {
+          if (o instanceof Error) {
```
Comment (gino-m) [inline web/src/app/services/submission/submission.service.ts:90]: You could also use ".filter(filterAndLogError)" above to avoid needing this in subscribe.

**Review by gino-m — CHANGES_REQUESTED** [review]
`Error--`! A few small readability suggestions, LG!

File: web/src/app/services/submission/submission.service.ts (hunk 4 above)
Comment (DaoyuT) [reply web/src/app/services/submission/submission.service.ts]: Done.

File: web/src/app/services/data-store/data-store.service.ts (hunk 3 above)
Comment (DaoyuT) [reply web/src/app/services/data-store/data-store.service.ts]: Done.

File: web/src/app/converters/firebase-data-converter.ts (hunk 1 above)
Comment (DaoyuT) [reply web/src/app/converters/firebase-data-converter.ts:484]: Added TSDoc mentioning that this method handles errors. What do you mean by `this can never happen`?

Comment (gino-m) [reply web/src/app/converters/firebase-data-converter.ts:484]: Thanks! Re "this", I was referring to job.tasks being `null` or `undefined`. It can never happen if we checked it previously. If that's not the case, we should also handle this case.

**Review by gino-m — CHANGES_REQUESTED** [review]
Thanks for the edits!

File: web/src/app/converters/firebase-data-converter.ts (hunk 1 above)
Comment (DaoyuT) [reply web/src/app/converters/firebase-data-converter.ts:484]: Got it, we did check `job.tasks` before this. I changed the TSDoc regarding this and changed the null/undefined check a bit.

**Review by gino-m — APPROVED** [review]
LGTM! 👍
