### PR TITLE
Fix GeoJSON properties order

### LINKED ISSUE #2252: Export GeoJSON properties order issue
Export GeoJSON have a different properties order than Export CSV

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #2252

### CODE REVIEW

File: functions/src/export-geojson.ts [hunk 1]
```diff
@@ -146,13 +147,13 @@ function getFileName(jobName: string | null) {
 
 function propertiesPbToModel(pb: {
   [k: string]: Pb.LocationOfInterest.IProperty;
-}): Map<string, string | number> {
-  const properties: {[k: string]: string | number} = {};
-  for (const k of Object.keys(pb)) {
-    const v = pb[k].stringValue || pb[k].numericValue;
+}): [string, string | number][] {
+  const entries: [string, string | number][] = [];
+  for (const k of Reflect.ownKeys(pb)) {
```
Comment (gino-m) [inline functions/src/export-geojson.ts]: Is this attempting to preserve the order of properties as they appear in the map in the db? Does that map preserve order, all the way from import to how they're persisted in Firestore?

Comment (rfontanarosa) [reply functions/src/export-geojson.ts]: the problem was not the order itself but the costincency with the CSV order.

In any case, at some point the order change.

This is what we have in the DocumentData:

```
name: { '1': 'ttt' },
whisp_plotId: { '1': '1' },
whisp_external_id: { '1': 'null' },
whisp_Area: { '2': 0.03500000014901161 },
whisp_Geometry_type: { '1': 'Polygon' },
```

this is what the firebase console shows (it probably applies a sort):

Screenshot 2025-09-26 alle 17 16 53

this is what we have after conversion (toMessage(row.data(), Pb.LocationOfInterest)):

```
    "whisp_nBR_PRODES_deforestation_Brazil_before_2020": 0,
    "whisp_nBR_MapBiomas_col9_coffee_2020": 0,
    "whisp_ESRI_2023_crop": 0,
    "whisp_European_Primary_Forest": 0,
```

so probably the solution is sort the keys at convertion time (the default one is fine for now) so we can have the control of it:

```
function propertiesPbToObject(pb: {
  [k: string]: Pb.LocationOfInterest.IProperty;
}): {[k: string]: string | number} {
  const properties: {[k: string]: string | number} = {};
  for (const k of Object.keys(pb).sort()) {
    const v = pb[k].stringValue || pb[k].numericValue;
    if (v !== null && v !== undefined) {
      properties[k] = v;
    }
  }
  return properties;
}

```

**Review by gino-m — CHANGES_REQUESTED** [review]
LGTM, please add test to verify ordering.
