### PR TITLE
[CSV Export] Add support for arbitrarily large exports

### LINKED ISSUE #2091: [Export CSV] Support large export of large datasets
CERSGIS was trying to export 2.5MB of data and the Cloud Function failed with OOM. This required @rfontanarosa to increase the amount of available to by Cloud Functions. We will eventually hit that limit as well; instead we should try to stream the data as we were doing before rather than loading the entire dataset in memory on the server before sending.

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #2091

### CODE REVIEW

File: functions/src/common/query-iterator.ts [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+ * limitations under the License.
+ */
+
+import {
+  Query,
+  QueryDocumentSnapshot,
+  QuerySnapshot,
+} from 'firebase-admin/firestore';
+
+export class QueryIterator implements AsyncIterator<QueryDocumentSnapshot> {
```
Comment (gino-m) [inline functions/src/common/query-iterator.ts:23]: Please add TSDoc to all public classes and methods. Example generated from this code using Gemini:

```ts
/**
 * An async iterator that iterates over documents in a Firestore query.
 * 
 * This iterator fetches documents in batches, using the provided `pageSize`.
 * It orders the documents by the specified `orderField`.
 *
 * @example
 * ```typescript
 * const query = firestore.collection('cities').where('population', '>', 1000000);
 * const iterator = new QueryIterator(query, 100, 'population');
 *
 * for await (const doc of iterator) {
 *   console.log(doc.id, doc.data());
 * }
 * ```
 */
```

**Review by gino-m — CHANGES_REQUESTED** [review]

File: functions/src/export-csv.spec.ts [hunk 2]
```diff
@@ -254,10 +269,25 @@ describe('exportCsv()', () => {
       expectedCsv: [
         '"system:index","geometry","name","area","data:What is the meaning of life?","data:How much?","data:When?","data:Which ones?","data:Where are you now?","data:Take a photo","data:contributor_name","data:contributor_email","data:created_client_timestamp","data:created_server_timestamp"',
         '"POINT_001","POINT (125.6 10.1)","Dinagat Islands",3.08,"Submission 1",42,,,,,,,"1970-01-01T00:00:00.000Z","1970-01-01T00:00:00.000Z"',
-        '"POINT_001","POINT (125.6 10.1)","Dinagat Islands",3.08,"Submission 2",,"2012-03-08T12:17:24.000Z",,,,,,"1970-01-01T00:00:00.000Z","1970-01-01T00:00:00.000Z"',
+        '"POINT_001","POINT (125.6 10.1)","Dinagat Islands",3.08,"Submission 2",,"2012-03-08T12:17:24.000Z",,,,"display_name","address@email.com","1970-01-01T00:00:01.000Z","1970-01-01T00:00:01.000Z"',
         '"POINT_002","POINT (8.3 47.05)","Luzern",,,,,"AAA,BBB,Other: other","POINT (45 -123)","http://photo/url",,,"1970-01-01T00:00:00.000Z","1970-01-01T00:00:00.000Z"',
       ],
     },
+    {
+      desc: 'export points w/wo/submissions',
```
Comment (gino-m) [inline functions/src/export-csv.spec.ts:277]: Please also add test for `submissions w/o LOIs are skipped`.

**Review by gino-m — CHANGES_REQUESTED** [review]

File: functions/src/export-csv.spec.ts (hunk 2 above)
[the remark this answers is not in the document]
Comment (rfontanarosa) [reply functions/src/export-csv.spec.ts:277]: sorry, i meant with AND without

Comment (rfontanarosa) [reply functions/src/export-csv.spec.ts]: is `export points w and w/o submission` ok?

**Review by gino-m — APPROVED** [review]
