### PR TITLE
Hide Job/Loi Menu when no Lois are available + Various fixes

### LINKED ISSUE #1613: [Submissions list] Don't show dropdown arrow if there are no LOIs
**Describe the bug**
If there are no LOIs for a job, we should not show the dropdown arrow
image

### PR DESCRIPTION
**Pull request by rfontanarosa**
closes #1613
part of #2149

https://github.com/user-attachments/assets/8ebbbcb8-f1e7-45ef-bdca-5c0c360542c0

### CODE REVIEW

File: web/src/app/components/job-list-item/job-list-item.component.ts [hunk 1]
```diff
@@ -82,18 +82,14 @@ export class JobListItemComponent implements OnInit, OnDestroy {
...
-        /* expandable= */ true,
-        /* iconName= */ 'label',
-        /* iconColo= */ this.job!.color!,
-        /* jobId= */ this.job!.id
-      ),
-    ]);
+    this.subscription.add(
+      this.loiService.getLocationsOfInterest$().subscribe(lois => {
+        console.log(this.job!.name, lois.size);
+        this.dataSource.data = this.dataSource.data.concat([
```
Comment (gino-m) [inline web/src/app/components/job-list-item/job-list-item.component.ts:88]: Is there a way to do this without relying on side effects? Can you instead use `*ngIf=` and look at the LOI count, for example?

**Review by gino-m — CHANGES_REQUESTED** [review]

**Review by gino-m — APPROVED** [review]
