### PR TITLE
Fixed zoom and pan when Point/Polygons selection

### LINKED ISSUE #1452: [Home screen] Map doesn't pan and zoom when site selected
https://github.com/google/ground-platform/assets/10047945/ede55282-d1f9-423c-aaa8-f35dcf3b25cd

### LINKED ISSUE #1542: [Submission list] Clicking on item text in submission list has no effect
Only clicks on the ">" work. Instead, the whole item should be clickable.

@amysorto PTAL?

### PR DESCRIPTION
**Pull request by rfontanarosa**
close #1452

https://github.com/google/ground-platform/assets/10047945/cd00e506-83f9-4f23-a7e8-da8359c97ba1

### CODE REVIEW

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 1]
```diff
@@ -434,46 +448,51 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
-    }
+
+    const bounds = new google.maps.LatLngBounds();
+
+    polygons?.forEach(polygon => {
+      polygon.setOptions({strokeWeight: enlargedPolygonStrokeWeight});
+
+      polygon.getPath().forEach(path => {
+        const point = new google.maps.LatLng(path.lat(), path.lng());
+        bounds.extend(point);
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:478]: I believe we already have a helper function which does this. Try searching for ".extend(" in the codebase. If not, perhaps this logic should be moved to Polygon or a helper somewhere.

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 2]
```diff
@@ -434,46 +448,51 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
+      });
+
+      this.map.googleMap?.fitBounds(bounds);
+    });
+  }
+
+  private unselectPolygons() {
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:485]: This code can be simplified:

if (this.selectedLoiIds) {
  Do stuff
}

Without the initial assignment.

**Review by gino-m — CHANGES_REQUESTED** [review]
Nice!

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 3]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
-  private selectPolygons(locationOfInterestId: string | null) {
-    const polygons = locationOfInterestId
-      ? this.polygons.get(locationOfInterestId)
-      : undefined;
-    if (polygons) {
-      for (const polygon of polygons) {
-        polygon.setOptions({strokeWeight: enlargedPolygonStrokeWeight});
+  private selectMarker(locationOfInterestId: string | null) {
+    if (locationOfInterestId) {
+      const marker = this.markers.get(locationOfInterestId);
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:444]: Please use short-circuit return to avoid code-nesting hadouken 💨 :

```ts
if (!locationofInterestId) return;
const marker = ...
```

Maybe what does `this.panAndZoom(marker?.getPosition())` do when `marker` is null or undefined?

Lastly, you can simplify further with:

```ts
marker.setDraggable(this.shouldEnableDrawingTools);
```

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 4]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
-      : undefined;
-    if (selectedPolygons) {
-      for (const polygon of selectedPolygons)
-        polygon.setOptions({
-          strokeWeight: normalPolygonStrokeWeight,
-        });
+  }
+
+  private unselectMarker() {
+    if (this.selectedLocationOfInterestId) {
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:457]: Same comment here re returning early.

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 5]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
+      const selectedMarker = this.markers.get(
+        this.selectedLocationOfInterestId
+      );
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:460]: And here

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 6]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
+
+      if (selectedMarker) {
+        this.setIconSize(selectedMarker, normalIconScale);
+        selectedMarker.setDraggable(false);
+      }
+    }
+  }
+
+  private selectPolygons(locationOfInterestId: string | null) {
+    if (locationOfInterestId) {
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:470]: Here as well

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 7]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
+      );
+
+      this.fitMapToLocationsOfInterest(
+        this.getLoisByIds(List([locationOfInterestId]))
+      );
+    }
+  }
+
+  private unselectPolygons() {
+    if (this.selectedLocationOfInterestId) {
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:484]: And here..

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts [hunk 8]
```diff
@@ -457,23 +439,60 @@ export class MapComponent implements AfterViewInit, OnDestroy {
...
+      const selectedPolygons = this.polygons.get(
+        this.selectedLocationOfInterestId
+      );
+
+      if (selectedPolygons) {
```
Comment (gino-m) [inline web/src/app/pages/main-page-container/main-page/map/map.component.ts:489]: Here too :)

**Review by gino-m — CHANGES_REQUESTED** [review]
A few more nits, thanks for the edits!

File: web/src/app/pages/main-page-container/main-page/map/map.component.ts (hunk 3 above)
Comment (rfontanarosa) [reply web/src/app/pages/main-page-container/main-page/map/map.component.ts]: there was a check if marker is null or not. so that question mark was useless. my bad.

**Review by gino-m — COMMENTED** [review]
LGTM!

**Review by gino-m — APPROVED** [review]
LGTM!
